# Generated by Django 5.2 on 2025-04-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=25)),
                ('product_price', models.FloatField(default=0.0)),
                ('product_DiscPrice', models.FloatField(default=0.0)),
                ('product_category', models.CharField(max_length=50)),
                ('product_description', models.TextField(max_length=500)),
                ('product_image', models.CharField(max_length=300)),
            ],
        ),
    ]
