# Generated by Django 5.2 on 2025-04-19 18:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_DiscPrice',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('footwear', 'Footwear'), ('accessories', 'Accessories'), ('home_appliances', 'Home Appliances'), ('furniture', 'Furniture'), ('beauty', 'Beauty & Personal Care'), ('groceries', 'Groceries'), ('books', 'Books'), ('stationery', 'Stationery & Office Supplies'), ('toys', 'Toys & Games'), ('sports', 'Sports & Fitness'), ('automotive', 'Automotive'), ('jewelry', 'Jewelry'), ('healthcare', 'Healthcare & Wellness'), ('baby', 'Baby Products'), ('pet', 'Pet Supplies'), ('tools', 'Tools & Hardware'), ('music', 'Musical Instruments'), ('art', 'Art & Craft'), ('garden', 'Gardening & Outdoors'), ('software', 'Software'), ('gaming', 'Gaming'), ('watches', 'Watches'), ('bags', 'Bags & Luggage'), ('mobile_accessories', 'Mobile Accessories'), ('kitchen', 'Kitchenware'), ('lighting', 'Lighting & Fixtures'), ('cleaning', 'Cleaning & Household'), ('decor', 'Home Decor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
